
export const types = {
    NEW_NUMBER: "NEW_NUMBER",
    NEW_NUMBER2: "NEW_NUMBER2",
    ADD_NUMBER: "ADD_NUMBER",
    SUBTRACT_NUMBER: "SUBTRACT_NUMBER",
    MULTIPLY_NUMBER: "MULTIPLY_NUMBER",
    DIVIDE_NUMBER: "DIVIDE_NUMBER"
}